### PR TITLE
WIP Markup

### PR DESCRIPTION
**Pull request by bsima**
Started work on parsing orgmode markup. Will continue later today / rest of the week, hope to finish this by Friday, June 15.

---

Todos:

- [x] Emphasis
    - [x] Bold
    - [x] Italic
    - [x] Strikethrough
    - [x] Underline
    - [x] Superscript
    - [x] Subscript
    - [x] Code / monospaced

---

If interested, I'm publishing the timelapses of me working on this

- [Part 1](https://www.youtube.com/watch?v=W4cq_wdpltQ)
- [Part 2](https://youtu.be/0TbNzFsMrAU)

### CODE REVIEW

**Comment by bsima** [comment]
Okay, I’ll clean it up, assign it, and ping you when it’s ready.

**Comment by zhujinxuan** [comment]
Hi, thank you for your work for supporting markup.


I am not sure whether I make something wrong.  But it seems that it does not support nested markup like:

```
/ italic * italic and bold * italic / 
```

**Comment by bsima** [comment]
You are correct. Do you have advice on how to write such a recursive parser? This is not something I’ve learned how to do yet. 

I’m away this week and next (busy month) but starting in August I will return to regular coding and contributions.

**Comment by zhujinxuan** [comment]
@bsima It is a bit complex, which means 
```
newtype Markup = {marks : [Mark], Text: String}
```
and the parser shall be a function of parser rather than `content !== '*'`;

Could you give me the permission of your fork in this branch that I can work directly on your PR?   I may do it in next Saturday to fix it.  (Because recently I am trying to mark a org-mode plugin of neovim based on `nvim-hs`)

**Comment by bsima** [comment]
Okay thanks, I think I understand.

You should be able to clone my branch locally like:

```sh
git remote add bsima https://github.com/bsima/orgmode-parse.git
git fetch bsima
git checkout name-of-my-branch
```

Then you'll have all my commits. You'll just have to open a new PR.

**Comment by ixmatus** [comment]
@bsima @zhujinxuan can you tell me the status of this work? I have some free-time coming up and I would like to get the markup parsing across the finish line and I would like to work off of whatever work you both have begun.

**Comment by zhujinxuan** [comment]
@ixmatus I am working on something else now.  I have not yet begun the markup parsing yet.

**Comment by bsima** [comment]
I have free time this week to work on it. I'll plan to work on it today or
tomorrow. If you want to work together on it (pair programming or otherwise) let
me know!

Everything I've done so far has been published in the PR.

**Comment by zhujinxuan** [comment]
@ixmatus Hi, I am working on the markups.  I have a question for `SectionParagraph`.  Does the current parser support multi-paragraph?

Like

```
* Headline 1
paragraph1
paragraph1
paragraph1

paragraph2
paragraph2
paragraph2
```

**Comment by zhujinxuan** [comment]
Hi, @ixmatus .  Shall we close this as https://github.com/ixmatus/orgmode-parse/pull/42 is merged?

**Comment by ixmatus** [comment]
@zhujinxuan yeah sure.

**Pull request closed without merging**
