### PR TITLE
Add hlint and most current GHC version test in travis CI

### PR DESCRIPTION
**Pull request by zhujinxuan**
1. Add hlint to style code
<del>2. Add GHC=head to ensure the package works with the updated GHC </del>
2. Support GHC 8.4.3, most current ghc except head

### CODE REVIEW

**Comment by zhujinxuan** [comment]
@ixmatus Hi, it is still work in progress.  I need to remove hlint errors and enable cache (so travis do not need to download all packages for each commit). 

I think I will finish it by this Sunday.

**Comment by ixmatus** [comment]
Oh thanks for pointing that out, I didn't see the `[WIP]` in your title!

**Comment by zhujinxuan** [comment]
@ixmatus Hi, the PR is ready for review~

1. changes: lint code according to hlint's suggestion : (prefer functor than monad, remove redundant parenthesis, use neater expressions)
2. compat with GHC 8.4.3
3. use stack to run travis, enable travis cache

**Comment by ixmatus** [comment]
@zhujinxuan so sorry! For some reason I didn't see your comment six days ago. Reviewing now.

**Pull request merged**
