### PR TITLE
Fix more bullet lists issues, add tests

### PR DESCRIPTION
**Pull request by volhovm**
The issue in https://github.com/ixmatus/orgmode-parse/issues/35 was not fully resolved, as the problem was still there, but with planning keywords instead. I've fixed it and added related tests.

I've also updated LTS version (ghc `8.4.3` is not part of the nixpkgs). Which version am I supposed to use btw, given that `3.0.0` is not (for some reason) recommended?

### CODE REVIEW

**Comment by ixmatus** [comment]
Thank you for the contribution! If you can fix the linter warnings (which look trivial) this should be good to go: https://travis-ci.org/ixmatus/orgmode-parse/jobs/595696083.

**Comment by ixmatus** [comment]
@volhovm unfortunately there's some problems with the markup parsers that completely breaks orgmode-parse and I haven't had any time to devote to fixing it. So, you can make the change against master and we could branch off of the commit before the markup parsers were introduced and do more patch releases.

**Comment by volhovm** [comment]
@ixmatus So you suggest me to rebase onto some 0.2.2 commit? Which particular one? df640a909f57888625038dd06a199991f312a2a9 ?

**Comment by ixmatus** [comment]
@volhovm no I think it's fine for this PR to go against master, once we merge it I can branch and then cherry-pick this commit to do a patch release, so don't worry about doing any that.

**Comment by ixmatus** [comment]
I don't have time to backport the change today but I will do that tomorrow and cut a new patch release to hackage.

**Comment by ixmatus** [comment]
I was busier than I thought I'd be yesterday, I'll handle the release later this afternoon.

**Comment by volhovm** [comment]
Have you released the new version?

**Comment by ixmatus** [comment]
I'm sorry, not yet. I had some urgent personal matters pop up. I'll try to get to it tomorrow morning, thanks got your patience.

**Comment by ixmatus** [comment]
@volhovm I did the backport but I'm heading out for some vacation / weekend fun stuff so I won't get to a hackage release until later today or tomorrow morning.

**Comment by volhovm** [comment]
Hi @ixmatus, sorry to bother you, but is the fix somewhere on the hackage already?

**Comment by ixmatus** [comment]
@volhovm it is not, I've been dealing with a very emotional personal life, moving my home/office, etc. Thanks for your patience, I will try to get a release out today (it shouldn't take me very long to do).

**Pull request merged**
